name: Publish Docker image

on:
  push:
    branches: main

jobs:
  push_to_registry:
    name: Push Docker image to registry
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.unidentifieddeveloper.com
          username: ${{ secrets.UD_DOCKER_REGISTRY_USER }}
          password: ${{ secrets.UD_DOCKER_REGISTRY_PWD }}

      - name: Push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: docker.pkg.unidentifieddeveloper.com/picotorrent/peach:latest
